name: SBSynergyInterface
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pyyaml
  - bleak
  - fastapi
  - uvicorn
  - pydantic
  - pip
  - pip:
      - ultralytics
      - sahi
